sonar.projectKey=refbrancherrorNew
sonar.projectName=refbrancherrorNew
sonar.projectVersion=1.0
sonar.sources=src
sonar.host.url=http://localhost:9000
#sonar.branch.name=master
sonar.pullrequest.key=121
sonar.pullrequest.branch=feature/refBranchError
sonar.pullrequest.base=master
#sonar.pullrequest.github.repository=msicie/PNF_cirrus-node-status-storage
#sonar.branch.target=main
#sonar.projectCreation.mainBranchName=


